script:
# Declare STRING variable
- STRING="Downloading ballerina..."

# Declare variable for Ballerina version
- BALLERINA_VERSION=0.975.0
- DISTRIBUTION_NAME=ballerina-platform-$BALLERINA_VERSION

# Print STRING variable
- echo $STRING

# Download Ballerina dist
- wget https://product-dist.ballerina.io/downloads/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip

# Unzip the zip file
- unzip $DISTRIBUTION_NAME.zip

# Add Ballerina to the path variable
- export PATH=$PATH:$(pwd)/$DISTRIBUTION_NAME/bin

# Print Ballerina version
- ballerina version

# Change the directory
- cd guide/

# Initialize the Ballerina project
- ballerina init

# Run tests
- ballerina test airline_reservation
- ballerina test hotel_reservation
- ballerina test car_rental

